package betty-blocks:crud;

interface crud {
  use betty-blocks:data-api/data-api.{context};
  use betty-blocks:types/types.{json-string, model, property-mapping};

  create: func(context: context, model: model, mapping: property-mapping, validation-sets: option<list<string>>) -> result<json-string, string>;
  update: func(context: context, model: model, record-id: string, mapping: property-mapping, validation-sets: option<list<string>>) -> result<json-string, string>;
  delete: func(context: context, model: model, record-id: string) -> result<json-string, string>;
}


world component {
  import wasi:logging/logging@0.1.0-draft;
  import betty-blocks:types/types;
  import betty-blocks:data-api/data-api;
  export crud;
}
