
build:
    wash build

build-test:
    cargo build --manifest-path test-component/Cargo.toml --target wasm32-wasip2 --release
    cargo build --target wasm32-wasip2 --release
    cargo build --tests

test:
    cargo test --lib --bins

integration-test:
    cargo test --tests '*'

lint:
    cargo check

formatting *args:
    cargo fmt --all {{args}}

clippy:
    cargo clippy --all-targets --all-features -- -D warnings
