package betty-blocks:actions;

interface actions {
   use betty-blocks:types/types.{run-input, run-output, error};
   
   call: func(input: run-input) -> result<run-output, error>;
   health: func() -> result<string, string>;
}