package betty-blocks:data-api;

interface data-api {

    record context {
        application-id: string,
        action-id: string,
        log-id: string,
        encrypted-configurations: option<list<string>>,
        jwt: option<string>,
    }

    request: func(context: context, query: string, variables: string) -> result<string, string>;
}