package betty-blocks:types;

interface types {
   type json-string = string;

   record payload {
      input: json-string,
      configurations: json-string,
   }

   record input {
      action-id: string,
      payload: payload,
   }

   record output {
      %result: json-string,
   }

   record model {
      name: string
   }

   record object-field {
      name: string,
   }

   record property-path {
      name: string,
      kind: string,
      object-fields: option<list<object-field>>
   }

   record property-map {
      key: list<property-path>,
      value: option<json-string>
   }

   type property-mapping = list<property-map>;
}