package wasmcloud:mcp@0.1.0;

world mcp {
    import betty-blocks:auth/jwt;
    import wasi:http/types@0.2.2;
    import wasi:config/store@0.2.0-rc.1;
    import betty-blocks:actions/actions;
    export wasi:http/incoming-handler@0.2.2;
}